"""add subscription renew field

Revision ID: 15ab0d3c5207
Revises: f044b3b6edc5
Create Date: 2019-04-16 16:34:15.548748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ab0d3c5207'
down_revision = 'f044b3b6edc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('renew', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'renew')
    # ### end Alembic commands ###
