"""Company owner

Revision ID: 198579220231
Revises: 65b67d4e55b4
Create Date: 2019-04-03 17:37:17.871640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '198579220231'
down_revision = '65b67d4e55b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'])
    op.drop_column('company', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('owner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_ibfk_1', 'company', 'user', ['owner'], ['id'])
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###
