"""adds company image

Revision ID: 1fd3b5d65d00
Revises: 15ab0d3c5207
Create Date: 2019-04-17 15:11:22.297076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd3b5d65d00'
down_revision = '15ab0d3c5207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'image')
    # ### end Alembic commands ###
