"""adduser name and surname

Revision ID: 4008b24e0c07
Revises: ea9c4ce4594f
Create Date: 2019-04-15 14:18:21.830526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4008b24e0c07'
down_revision = 'ea9c4ce4594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phone', sa.Numeric(), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
