"""company membership with backref

Revision ID: b8d529888ca9
Revises: 9c3fdc4ca5cc
Create Date: 2019-04-16 10:46:44.348182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d529888ca9'
down_revision = '9c3fdc4ca5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('membership_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'membership', ['membership_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'membership_id')
    # ### end Alembic commands ###
