"""adds subscription tables visibility

Revision ID: f044b3b6edc5
Revises: 85ba1a1011c9
Create Date: 2019-04-16 16:07:42.902720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f044b3b6edc5'
down_revision = '85ba1a1011c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('visible', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'active')
    op.drop_column('product', 'visible')
    # ### end Alembic commands ###
